#!/usr/bin/perl
######################################################################
#  A lancher script for supporting a script link in local mozilla
#  presentations.
######################################################################

open(LOG, ">>/home/dov/tmp/launch.log");
print LOG "----------\n";
print LOG "pwd = ", `pwd`;
print LOG "ARGV = @ARGV\n";
close(LOG);

my $cmd = shift;
$cmd=~ s/script://;
system "chmod +x $cmd; /bin/env GTK2_RC_FILES=lecture-gtkrc-2.0 ./$cmd &";
